import Foundation

public struct IgnoreDecision: Equatable {
    public enum Reason: Equatable {
        case concealed, transient, autoGenerated, blockedApp, tooLarge, ownApp
    }
    public let reason: Reason?
    public var shouldStore: Bool { reason == nil }
    public init(reason: Reason?) { self.reason = reason }
}

/// Отказ от записи. Три служебных типа — соглашение nspasteboard.org, которым
/// менеджеры паролей просят не сохранять содержимое. Игнорировать его нельзя:
/// иначе пароли лягут в нашу историю на диск.
public struct IgnoreRules: Sendable {
    public static let defaultBlocked: Set<String> = [
        "com.1password.1password",
        "com.1password.1password7",
        "com.agilebits.onepassword",
        "com.apple.keychainaccess",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
    ]

    private let blocked: Set<String>
    private let own: String

    public init(blockedBundleIDs: Set<String> = IgnoreRules.defaultBlocked, ownBundleID: String) {
        blocked = blockedBundleIDs
        own = ownBundleID
    }

    public func decide(types: [String], sourceBundleID: String?, byteCount: Int) -> IgnoreDecision {
        if types.contains("org.nspasteboard.ConcealedType") { return .init(reason: .concealed) }
        if types.contains("org.nspasteboard.TransientType") { return .init(reason: .transient) }
        if types.contains("org.nspasteboard.AutoGeneratedType") { return .init(reason: .autoGenerated) }
        if let id = sourceBundleID {
            if id == own { return .init(reason: .ownApp) }
            if blocked.contains(id) { return .init(reason: .blockedApp) }
        }
        if byteCount > Config.History.maxImageBytes { return .init(reason: .tooLarge) }
        return .init(reason: nil)
    }
}
