import AppKit
import Foundation

public struct IgnoreDecision: Equatable {
    public enum Reason: Equatable {
        case concealed, transient, autoGenerated, blockedApp, tooLarge, ownApp
    }
    public let reason: Reason?
    public var shouldStore: Bool { reason == nil }
    public init(reason: Reason?) { self.reason = reason }
}

/// Отказ от записи. Три служебных типа — соглашение nspasteboard.org, которым
/// менеджеры паролей просят не сохранять содержимое. Игнорировать его нельзя:
/// иначе пароли лягут в нашу историю на диск.
public struct IgnoreRules: Sendable {
    public static let defaultBlocked: Set<String> = [
        "com.1password.1password",
        "com.1password.1password7",
        "com.agilebits.onepassword",
        "com.apple.keychainaccess",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
    ]

    private let blocked: Set<String>
    private let own: String

    public init(blockedBundleIDs: Set<String> = IgnoreRules.defaultBlocked, ownBundleID: String) {
        blocked = blockedBundleIDs
        own = ownBundleID
    }

    public func decide(types: [String], sourceBundleID: String?, byteCount: Int) -> IgnoreDecision {
        if types.contains("org.nspasteboard.ConcealedType") { return .init(reason: .concealed) }
        if types.contains("org.nspasteboard.TransientType") { return .init(reason: .transient) }
        if types.contains("org.nspasteboard.AutoGeneratedType") { return .init(reason: .autoGenerated) }
        if let id = sourceBundleID {
            if id == own { return .init(reason: .ownApp) }
            if blocked.contains(id) { return .init(reason: .blockedApp) }
        }
        if byteCount > sizeLimit(for: types) { return .init(reason: .tooLarge) }
        return .init(reason: nil)
    }

    /// Картинки и текст мерятся разными пределами. Раньше предел был один,
    /// картиночный: текст на сорок мегабайт проходил в историю, хотя лежать ему
    /// предстояло прямо в `index.json`, который перезаписывается на каждое
    /// изменение.
    private func sizeLimit(for types: [String]) -> Int {
        types.contains(where: Self.imageTypes.contains)
            ? Config.History.maxImageBytes
            : Config.History.maxTextBytes
    }

    /// Ровно те два типа, которые `SystemPasteboard` читает как картинку. Список
    /// обязан совпадать с ним, а не быть шире: предел должен выбираться по тому
    /// же признаку, по которому запись потом становится картинкой, иначе решение
    /// и хранение разойдутся.
    private static let imageTypes: Set<String> = [NSPasteboard.PasteboardType.png.rawValue,
                                                  NSPasteboard.PasteboardType.tiff.rawValue]
}
