import Foundation

public struct IgnoreDecision: Equatable {
    public enum Reason: Equatable {
        case concealed, transient, autoGenerated, blockedApp, tooLarge, ownApp
    }
    public let reason: Reason?
    public var shouldStore: Bool { reason == nil }
    public init(reason: Reason?) { self.reason = reason }
}

/// Отказ от записи. Три служебных типа — соглашение nspasteboard.org, которым
/// менеджеры паролей просят не сохранять содержимое. Игнорировать его нельзя:
/// иначе пароли лягут в нашу историю на диск.
public struct IgnoreRules: Sendable {
    public static let defaultBlocked: Set<String> = [
        "com.1password.1password",
        "com.1password.1password7",
        "com.agilebits.onepassword",
        "com.apple.keychainaccess",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
    ]

    private let blocked: Set<String>
    private let own: String
    private let maxBytes: Int

    /// Потолок размера приходит снаружи: его крутит человек в настройках, а
    /// значение из `Config` остаётся значением по умолчанию.
    public init(blockedBundleIDs: Set<String> = IgnoreRules.defaultBlocked,
                ownBundleID: String,
                maxBytes: Int = Config.History.maxImageBytes) {
        blocked = blockedBundleIDs
        own = ownBundleID
        self.maxBytes = maxBytes
    }

    public func decide(types: [String], sourceBundleID: String?, byteCount: Int) -> IgnoreDecision {
        if types.contains("org.nspasteboard.ConcealedType") { return .init(reason: .concealed) }
        if types.contains("org.nspasteboard.TransientType") { return .init(reason: .transient) }
        if types.contains("org.nspasteboard.AutoGeneratedType") { return .init(reason: .autoGenerated) }
        if let id = sourceBundleID {
            if id == own { return .init(reason: .ownApp) }
            if blocked.contains(id) { return .init(reason: .blockedApp) }
        }
        if byteCount > maxBytes { return .init(reason: .tooLarge) }
        return .init(reason: nil)
    }
}
