import Testing
@testable import ChelkaCore

private let rules = IgnoreRules(ownBundleID: "com.adylenya.4elka")

@Test func skipsConcealedType() {
    let d = rules.decide(types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"],
                         sourceBundleID: nil, byteCount: 10)
    #expect(d.reason == .concealed)
    #expect(!d.shouldStore)
}

@Test func skipsTransientAndAutoGeneratedTypes() {
    #expect(rules.decide(types: ["org.nspasteboard.TransientType"],
                         sourceBundleID: nil, byteCount: 1).reason == .transient)
    #expect(rules.decide(types: ["org.nspasteboard.AutoGeneratedType"],
                         sourceBundleID: nil, byteCount: 1).reason == .autoGenerated)
}

@Test func skipsBlockedApps() {
    #expect(rules.decide(types: ["public.utf8-plain-text"],
                         sourceBundleID: "com.1password.1password", byteCount: 1).reason == .blockedApp)
}

@Test func skipsOwnAppToAvoidFeedbackLoop() {
    #expect(rules.decide(types: ["public.utf8-plain-text"],
                         sourceBundleID: "com.adylenya.4elka", byteCount: 1).reason == .ownApp)
}

@Test func skipsOversizedPayload() {
    #expect(rules.decide(types: ["public.png"], sourceBundleID: nil,
                         byteCount: Config.History.maxImageBytes + 1).reason == .tooLarge)
}

@Test func storesOrdinaryText() {
    let d = rules.decide(types: ["public.utf8-plain-text"], sourceBundleID: "com.apple.Safari", byteCount: 20)
    #expect(d.shouldStore)
    #expect(d.reason == nil)
}

/// У текста свой предел, и он строже: текст лежит в `index.json` прямо в тексте,
/// а файл перезаписывается на каждое изменение истории. Раньше текст мерился
/// пределом для картинки, и дамп на сорок мегабайт спокойно проходил в историю.
@Test func oversizedTextIsJudgedByItsOwnLimit() {
    #expect(rules.decide(types: ["public.utf8-plain-text"], sourceBundleID: nil,
                         byteCount: Config.History.maxTextBytes + 1).reason == .tooLarge)
    #expect(rules.decide(types: ["public.utf8-plain-text"], sourceBundleID: nil,
                         byteCount: Config.History.maxTextBytes).shouldStore)
}

/// И обратное: картинку нельзя мерить пределом текста — обычный снимок большого
/// экрана крупнее двух мегабайт, и отказывать в нём нечего.
@Test func pictureLargerThanTheTextLimitIsStillStored() {
    #expect(rules.decide(types: ["public.png"], sourceBundleID: nil,
                         byteCount: Config.History.maxTextBytes + 1).shouldStore)
}

@Test func payloadAtExactLimitIsStored() {
    #expect(rules.decide(types: ["public.png"], sourceBundleID: nil,
                         byteCount: Config.History.maxImageBytes).shouldStore)
}
